#!/bin/bash

##PBS -o /car-data/wwilliams/bootes/multi_bootes/test_AGNfitter/AGNfitter 
##PBS -e /car-data/wwilliams/bootes/multi_bootes/test_AGNfitter/AGNfitter 
##PBS -k oe 
##PBS -j oe 

echo ------------------------------------------------------
echo -n 'Job is running on node(s) '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: ARRAYID = $PBS_ARRAYID
echo ------------------------------------------------------
echo

cd /car-data/wwilliams/bootes/multi_bootes/agnfitter

export PATH=/car-data/wwilliams/bootes/multi_bootes/agnfitter/git/AGNfitter/:$PATH

RUN_AGNfitter_multi.py --independent --sourcenumber $PBS_ARRAYID SETTINGS_AGNfitter_ww.py
